
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased flex items-center justify-center min-h-screen bg-github`}
      >
        {children}
      </body>
    </html>
  );
}
